CREATE TABLE `0_tasks`(
    `Rfrnc` BIGINT GENERATED BY DEFAULT,
    `Nm` VARCHAR(255),
    `Dscrptn` VARCHAR(255),
    `Cndntn` BOOLEAN,
    `Rmvd` BOOLEAN,
    `Lckd` BOOLEAN,
    `DtAdmssn` DATE,
    `ChckTm` TIME,
    CONSTRAINT pk_tasks PRIMARY KEY (`Rfrnc)
);